name = "hivechat"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
AUTH_SECRET = "kX9mZ2vN8qL4wR7yT1pA3sD6fG0hJ5iK"
AUTH_TRUST_HOST = "true"
NEXTAUTH_URL = "https://lisoexpo.de5.net"
ADMIN_CODE = "hivechat2024"
DATABASE_URL = "postgresql://neondb_owner:npg_LwDXAFnW6j2J@ep-tiny-fire-a12tzgkb-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
